// Generated by tools/font_baker — do not edit.
#pragma once

extern const unsigned char lumi_font_atlas_meta[];
extern const unsigned int  lumi_font_atlas_meta_len;
extern const unsigned char lumi_font_atlas_rgba_zstd[];
extern const unsigned int  lumi_font_atlas_rgba_zstd_len;
extern const unsigned int  lumi_font_atlas_rgba_len;
