// Generated by tools/font_baker — do not edit.
#pragma once

extern const unsigned char LUMI_FONT_ATLAS_META[];
extern const unsigned int  LUMI_FONT_ATLAS_META_LEN;
extern const unsigned char LUMI_FONT_ATLAS_RGBA_ZSTD[];
extern const unsigned int  LUMI_FONT_ATLAS_RGBA_ZSTD_LEN;
extern const unsigned int  LUMI_FONT_ATLAS_RGBA_LEN;
