lumi_msg("Fetching glslang")
lumi_fetch("glslang" "https://github.com/KhronosGroup/glslang.git" "e435148" GLSLANG_ROOT)

if(GLSLANG_ROOT)

    # build_info.h is normally generated by glslang's CMake from build_info.h.tmpl.
    # Template lives at repo root; tokens are @major@/@minor@/@patch@/@flavor@.
    set(_GLSLANG_GENERATED "${CMAKE_CURRENT_BINARY_DIR}/glslang_generated")
    file(READ "${GLSLANG_ROOT}/build_info.h.tmpl" _bi_tmpl)
    string(REPLACE "@major@"  "14" _bi_tmpl "${_bi_tmpl}")
    string(REPLACE "@minor@"  "0"  _bi_tmpl "${_bi_tmpl}")
    string(REPLACE "@patch@"  "0"  _bi_tmpl "${_bi_tmpl}")
    string(REPLACE "@flavor@" ""   _bi_tmpl "${_bi_tmpl}")
    file(WRITE "${_GLSLANG_GENERATED}/glslang/build_info.h" "${_bi_tmpl}")

    target_include_directories(luminoveau SYSTEM PUBLIC
        "${GLSLANG_ROOT}"
        "${GLSLANG_ROOT}/glslang"
        "${_GLSLANG_GENERATED}"
        "${_GLSLANG_GENERATED}/glslang"
    )

    target_compile_definitions(luminoveau PRIVATE
        ENABLE_SPIRV=1
        ENABLE_OPT=0
    )

    target_sources(luminoveau PRIVATE
        # C interface
        "${GLSLANG_ROOT}/glslang/CInterface/glslang_c_interface.cpp"

        # MachineIndependent front-end
        "${GLSLANG_ROOT}/glslang/MachineIndependent/glslang_tab.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/attribute.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/Constant.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/iomapper.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/InfoSink.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/Initialize.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/IntermTraverse.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/Intermediate.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/ParseContextBase.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/ParseHelper.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/PoolAlloc.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/RemoveTree.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/Scan.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/ShaderLang.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/SpirvIntrinsics.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/SymbolTable.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/Versions.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/intermOut.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/limits.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/linkValidate.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/parseConst.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/reflection.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/propagateNoContraction.cpp"

        # Preprocessor
        "${GLSLANG_ROOT}/glslang/MachineIndependent/preprocessor/Pp.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/preprocessor/PpAtom.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/preprocessor/PpContext.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/preprocessor/PpScanner.cpp"
        "${GLSLANG_ROOT}/glslang/MachineIndependent/preprocessor/PpTokens.cpp"

        # GenericCodeGen
        "${GLSLANG_ROOT}/glslang/GenericCodeGen/CodeGen.cpp"
        "${GLSLANG_ROOT}/glslang/GenericCodeGen/Link.cpp"

        # SPIRV output
        "${GLSLANG_ROOT}/SPIRV/GlslangToSpv.cpp"
        "${GLSLANG_ROOT}/SPIRV/InReadableOrder.cpp"
        "${GLSLANG_ROOT}/SPIRV/Logger.cpp"
        "${GLSLANG_ROOT}/SPIRV/SpvBuilder.cpp"
        "${GLSLANG_ROOT}/SPIRV/SpvPostProcess.cpp"
        "${GLSLANG_ROOT}/SPIRV/doc.cpp"
        "${GLSLANG_ROOT}/SPIRV/disassemble.cpp"
        "${GLSLANG_ROOT}/SPIRV/CInterface/spirv_c_interface.cpp"
    )

    if(WIN32)
        target_sources(luminoveau PRIVATE
            "${GLSLANG_ROOT}/glslang/OSDependent/Windows/ossource.cpp"
        )
        target_compile_definitions(luminoveau PRIVATE GLSLANG_OSINCLUDE_WIN32)
    else()
        target_sources(luminoveau PRIVATE
            "${GLSLANG_ROOT}/glslang/OSDependent/Unix/ossource.cpp"
        )
        target_compile_definitions(luminoveau PRIVATE GLSLANG_OSINCLUDE_UNIX)
    endif()

    lumi_done("glslang (source-only)")
else()
    lumi_warn("glslang - fetch failed")
endif()
